# Generated by Django 4.1.7 on 2023-03-25 14:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de celular')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Habilitado'), (False, 'Inhabilitado')], default=True, verbose_name='Estado')),
                ('discount_code', models.CharField(max_length=100, verbose_name='Código de descuento')),
                ('percentage', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Efectuada'), (2, 'Vencida')], default=0, verbose_name='Estado')),
                ('payment_link', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Link de pago')),
                ('value_1', models.IntegerField(blank=True, default=None, null=True, verbose_name='Valor inicial')),
                ('value_2', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor final')),
                ('validated_value', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Valor validado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Válido hasta')),
                ('x_ref_payco', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('x_description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('x_response', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('client', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.cliente', verbose_name='Cliente')),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.descuento', verbose_name='Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prize', models.CharField(max_length=200, verbose_name='Premio')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripción')),
                ('Lottery_date', models.DateField(verbose_name='Fecha de sorteo')),
                ('ballot_price', models.PositiveIntegerField(default=10000, verbose_name='Precio de las balotas')),
                ('min_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número mínimo')),
                ('max_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número máximo')),
                ('step', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Paso')),
                ('ballot_unavailable_time', models.DurationField(verbose_name='Tiempo de inhabilidad de las balotas')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sociedad', verbose_name='Sociedad')),
            ],
        ),
        migrations.CreateModel(
            name='EpaycoLateConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'OK'), (1, 'Por resolver')], default=0, verbose_name='Estado')),
                ('json_data', models.TextField(blank=True, default='', null=True, verbose_name='Datos Json')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('transaction', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.transaccion', verbose_name='Transacción')),
            ],
        ),
        migrations.AddField(
            model_name='descuento',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rifa', verbose_name='Sorteo'),
        ),
        migrations.CreateModel(
            name='Balota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('price', models.PositiveIntegerField(default=10000, verbose_name='Precio')),
                ('selected', models.BooleanField(default=False, verbose_name='Seleccionada')),
                ('unavailable_time', models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Tiempo de inhabilidad')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.rifa', verbose_name='Sorteo')),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.transaccion', verbose_name='Transacción')),
            ],
        ),
    ]
