# Generated by Django 4.1.7 on 2023-03-26 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone_number',
            field=models.PositiveIntegerField(verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='ballot_unavailable_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600), verbose_name='Tiempo de inhabilidad de las balotas'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la rifa'),
        ),
    ]
