# Generated by Django 4.1.7 on 2023-03-02 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cliente_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balota',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='balota',
            name='vendida',
        ),
        migrations.AddField(
            model_name='balota',
            name='transaccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.transaccion'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='valor_final',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MinValueValidator(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='valor_inicial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descuento',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Habilitado'), (False, 'Inhabilitado')], default=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='store.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Efectuada'), (False, 'Pendiente')], default=False),
        ),
    ]
