# Generated by Django 4.1.7 on 2023-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rifa_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rifa',
            old_name='Lottery_date',
            new_name='lottery_date',
        ),
        migrations.AlterField(
            model_name='rifa',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Está activa'),
        ),
    ]
