# Generated by Django 4.1.7 on 2023-03-02 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_balota_cliente_remove_balota_vendida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.cliente'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='link',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='valor_final',
            field=models.IntegerField(default=None, null=True, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='valor_inicial',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
