# Generated by Django 4.1.7 on 2023-03-02 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_transaccion_cliente_alter_transaccion_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='link',
            new_name='link_de_pago',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='valor_final',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
