# Generated by Django 4.1.7 on 2023-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_balota_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='display_percentage',
            field=models.BooleanField(default=False, verbose_name='Mostrar porcentaje de balotas vendidas'),
        ),
    ]
