# Generated by Django 4.1.7 on 2023-04-07 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rifa_display_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='min_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número mínimo'),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='step',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Paso'),
        ),
    ]
