# Generated by Django 4.1.7 on 2023-03-05 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_epaycoconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='balota',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 2, 22, 25, 10017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ref_epayco',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='valid_until',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.BooleanField(choices=[(0, 'Pendiente'), (1, 'Efectuada'), (2, 'Vencida')], default=False),
        ),
    ]
