# Generated by Django 4.1.7 on 2023-03-05 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_balota_time_period_transaccion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
