# Generated by Django 4.1.7 on 2023-03-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_transaccion_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Efectuada'), (2, 'Vencida')], default=False),
        ),
    ]
