# Generated by Django 4.1.7 on 2023-03-05 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('paso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_de_reserva', models.DurationField()),
                ('precio', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='balota',
            name='precio',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
