# Generated by Django 4.1.7 on 2023-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_transaccion_ref_epayco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='x_response',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
