# Generated by Django 4.1.7 on 2023-03-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_transaccion_x_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EpaycoConfirmation',
            new_name='EpaycoLateConfirmation',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='late_confirmation',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='valor_pagado',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='balota',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
