# Generated by Django 4.1.7 on 2023-03-24 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_epaycolateconfirmation_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lottery_date', models.DateField(verbose_name='Fecha de sorteo')),
                ('ballot_price', models.IntegerField()),
                ('valor_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor_mínimo')),
                ('valor_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor_máximo')),
                ('paso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tiempo_de_reserva', models.DurationField()),
                ('precio', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='rango',
            name='paso',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
